---

- name: Nginx example Playbook
  hosts: all
  tasks:
    - name: Display message
      debug:
        msg: "Starting initial configuration"

    - name: check service 8080
      shell: curl http://localhost:8080/
      register: curl1
    
    - name: show curl results
      debug:
      var: curl1.stdout_lines

    - name: check service 80
      shell: curl http://localhost:80/
      register: curl2
    
    - name: show curl results
      debug:
      var: curl2.stdout_lines
    
    - name: Reload Nginx
      service: 
        name: nginx
        state: reloaded
      become: yes